- name: Install Sonar Scanner (latest from zipball)
  run: |
    set -euo pipefail

    api="https://api.github.com/repos/SonarSource/sonar-scanner-cli/releases/latest"

    zip_url=$(curl -fsSL "$api" | grep -oP '"zipball_url":\s*"\K[^"]+')

    echo "Downloading: $zip_url"

    curl -L "$zip_url" -o /tmp/sonar-scanner.zip

    sudo unzip -q /tmp/sonar-scanner.zip -d /opt

    # The extracted folder name is dynamic: SonarSource-sonar-scanner-cli-<commit>
    dir=$(find /opt -maxdepth 1 -type d -name "SonarSource-sonar-scanner-cli-*")

    sudo ln -sfn "$dir/bin/sonar-scanner" /usr/local/bin/sonar-scanner

    sonar-scanner --version
