- name: Install Sonar Scanner
  run: |
    set -euo pipefail

    url="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-latest-linux-x64.zip"

    echo "Downloading Sonar Scanner from: $url"
    curl -fsSL "$url" -o /tmp/sonar-scanner.zip

    sudo unzip -q /tmp/sonar-scanner.zip -d /opt

    # The extracted folder already contains the version number
    sudo ln -sfn /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/sonar-scanner

    sonar-scanner --version
