- name: Install Sonar Scanner CLI
  run: |
    set -euo pipefail

    VERSION="8.0.1.6346"
    URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${VERSION}.zip"

    echo "Downloading Sonar Scanner ${VERSION}..."
    curl -fL "$URL" -o /tmp/sonar-scanner.zip

    echo "Installing to /opt/sonar-scanner..."
    sudo rm -rf /opt/sonar-scanner || true
    sudo unzip -q /tmp/sonar-scanner.zip -d /opt

    # The archive extracts to /opt/sonar-scanner-<version>
    sudo mv /opt/sonar-scanner-${VERSION} /opt/sonar-scanner

    # Make binary globally available
    sudo ln -sfn /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

    # Verify installation
    sonar-scanner --version
